### ISSUE TITLE
problem with install datfiles

### ISSUE THREAD

**Issue by desertsnow73** [mscoutermarsh/dotfiles#12]
I'm new to Vim and linux system. I watched your youtub 'Learning Vim in a Week'.
As you recommended I tried to install your dotfiles but failed.

Could you teach me how to install it?
![screenshot from 2017-11-16 11 54 40](https://user-images.githubusercontent.com/25863367/32929975-1c9bdac8-cb9f-11e7-9873-47943a980723.png)

**Comment by mscoutermarsh** [comment]
Hi @desertsnow73 😄 !

I think I have this fixed now. Can you try to install again?

You'll need to pull down the dotfiles again.

```
cd ~/.dotfiles/
git pull
./install
```

Let me know if you run into any other problems.

**Comment by desertsnow73** [comment]
Thank you, Mike 😊 !

It's installed without any problem. :)
I wish I can be a good programmer like you.

Thank you again.

Cheers~

Brad


On Sun, Nov 19, 2017 at 12:18 AM, Mike Coutermarsh <notifications@github.com

**Comment by mscoutermarsh** [comment]
😄
