### ISSUE TITLE
wrong symlink ?

### ISSUE THREAD

**Issue by sayduck-daniel** [mscoutermarsh/dotfiles#15]
I tried to install this dotfiles and at the end it seems my `init.vim` is symlinked to `/Users/mscoutermarsh/.dotfiles/vim/vimrc.symlink`

<img width="756" alt="screen shot 2018-07-01 at 11 11 11 am" src="https://user-images.githubusercontent.com/38907720/42132398-c1ab10c4-7d1f-11e8-8daa-0c10c34f5858.png">

I wonder it this is the usual behaviour or if this is a bug?

I have the same problem than #13 and I wonder if this could be the problem?

**Comment by mscoutermarsh** [comment]
@sayduck-daniel ahh, I found the problem but haven't finished a good fix yet.

If you update the `init.vim` symlink to `/Users/daniel/.dotfiles/vim/vimrc.symlink`

And rerun the install script, it should work.

I'm going to try to teach the install script to do this automatically.
