### ISSUE TITLE
tmux - duplicate setting

### ISSUE THREAD

**Issue by tylerfowle** [mscoutermarsh/dotfiles#17]
https://github.com/mscoutermarsh/dotfiles/blob/4c520f8eb9c3c642159d8dc77e45962f4790e8e5/tmux/tmux.conf.symlink#L18

https://github.com/mscoutermarsh/dotfiles/blob/4c520f8eb9c3c642159d8dc77e45962f4790e8e5/tmux/tmux.conf.symlink#L95

**Comment by mscoutermarsh** [comment]
Fixed! thank you
